### PR TITLE
Open the note after create it

### PR DESCRIPTION
**Pull request by netoguimaraes**
this is related to the #15 .

When a user creates a new note this note will be opened automatically, ready for receive content. This is a UX improvement.

### CODE REVIEW

**Comment by netoguimaraes** [comment]
@Hyuchia @fsvdr  someone can give me a feedback about it?

**Comment by Hyuchia** [comment]
Hi There! Sorry for the delay, got some really busy weeks, I've tested it and works just fine! I think the fact it didn't open right away was a inheritance of older versions that had some limitations to do it but this works great! However, I'm not sure the call to `show("notes")` is necessary since it will show the notes and as soon as the note is decrypted, it will change to the editor or is there a reason to show the notes first?

**Comment by netoguimaraes** [comment]
Yeah, it's not necessary. I removed it in the last commit. Thanks

**Comment by Hyuchia** [comment]
Great, thanks a lot! I think this is kind of an expected behavior by everyone so it's great to have it now :)

**Pull request merged**
